# Generated by Django 2.2.9 on 2020-01-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200126_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FreshMan'), (2, 'Senior')], default=1),
        ),
    ]
